---
  - name: MariaDB Install
    yum: name={{ item }}
    with_items:
     - mariadb-server
    register: mariadbinstalled

  - name: MariaDB my.cnf
    when: mariadbinstalled|success
    action: template src=my.cnf.j2 dest=/etc/my.cnf
    register: my_cnf_copied

  - name: Starting MariaDB 
    when: my_cnf_copied|success
    service: name=mariadb state=started
    register: mariadbstarted
 
  - name: Enabled MariaDB Service
    when: mariadbinstalled|success
    service: name=mariadb enabled=true
   
  - name: Ensure DB user exists
    when: mariadbstarted|success
    mysql_user: name={{ cl_db_user }}  password={{ cl_db_pass }} priv='copperleaf.*:ALL' state=present
    register: mariadbusers

  - name: Ensure DB exists
    when: mariadbstarted|success
    mysql_db: name=copperleaf state=present
    register: cldbcreated






  - name: Import CopperLeafDB
    when: mariadbusers|success
    mysql_db: name=copperleaf state=import target=/tmp/db/copperleaf_sql.bz2
