---
  - name: Apache httpd Package
    yum: pkg=httpd state=installed
 
  - name: Enable Apache Event MPM
    copy: src=00-mpm.conf dest=/etc/httpd/conf.modules.d/00-mpm.conf

  - name: Enable Copper Leaf local configuration
    copy: src=local.copperleaf.conf dest=/etc/httpd/conf.d/local.copperleaf.conf
    notify: Restart Apache
    register: copperleafcopied

  - name: Set SELinux to permissive 
    selinux: policy=targeted state=permissive

  - name: Ensure Apache is started
    when: copperleafcopied|success
    service: name=httpd state=started enabled=yes
    
